

SET hive.exec.dynamic.partition = true; 
SET hive.exec.dynamic.partition.mode = nonstrict;

INSERT OVERWRITE TABLE CDW_SAPPBRANCH
PARTITION(BRANCH_STATE) 
select  
BRANCH_CODE,
BRANCH_NAME,
BRANCH_STREET, 
BRANCH_CITY, 
BRANCH_ZIP,
BRANCH_PHONE,
LAST_UPDATED,
BRANCH_STATE FROM STAGING_CDW_SAPP_BRANCH;